service: davis-custom-action-example

provider:
  name: aws
  runtime: nodejs6.10

functions:
  ticket:
    handler: index.handler
    events:
      - http:
          path: event
          method: post
